@startuml
'https://plantuml.com/class-diagram


class Inventory {
    -map<String,InventoryItem>
    -ArrayList<InventoryItem>

    +InventoryItem createInventoryItem(String serialNumber, String name, double price)
    +void addItem(InventoryItem item)
    +void removeItem(InventoryItem item)
    +void clearList()
    +void editItemName(String newName)
    +void editItemSerialNumber(String newSerial)
    +boolean isValidSerial(String serialNumber)
    +boolean isAlreadySerial(String serial)
    +void readFile(File file)
    +void writeFile(File file)
    +void tsbReader(File file))
    +void htmlReader(File file)
    +void jsonReader(File file)
    +void tsbWriter(File file)
    +void htmlWriter(File file)
    +void jsonWriter(File file)
}

class InventoryItem{
    -String serialNumber
    -String name
    -double price

}

Inventory*--InventoryItem

@enduml